apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworks.aws.platform.upbound.io
spec:
  group: aws.platform.upbound.io
  names:
    categories:
    - crossplane
    kind: XNetwork
    plural: xnetworks
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: XNetwork is the Schema for the XNetwork API.
        properties:
          spec:
            description: XNetworkSpec defines the desired state of XNetwork.
            properties:
              deletionPolicy:
                default: Delete
                description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                type: string
                enum: [ "Delete", "Orphan" ]
              id:
                type: string
              region:
                type: string
              subnets:
                items:
                  properties:
                    availabilityZone:
                      type: string
                    cidrBlock:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              vpcCidrBlock:
                type: string
            type: object
          status:
            description: XNetworkStatus defines the observed state of XNetwork.
            type: object
        required:
        - spec
        type: object
    served: true
